name: Martial Art and World View
favicon: null
layout_spectrum: 0.8615968946833163
typography_spectrum: 0.9234058212023228
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5444876591209322
  lightness: 0.529003664618358
  saturation: 0.4171307554934174
  rhythmicContrast: 0.35514877340756357
purpose: []
